Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  KeyPairName:
    Description: Select Key Pair .
    Type: AWS::EC2::KeyPair::KeyName  

Mappings: 
  AMIRegionMap: 
    us-east-1: 
      AMI: "ami-0ff8a91507f77f867"
    us-east-2: 
      AMI: "ami-0bdb828fd58c52235"
    us-west-1: 
      AMI: "ami-047bb4163c506cd98"
    
Resources:
  EC2Instance:
      Type: AWS::EC2::Instance
      Metadata: 
        AWS::CloudFormation::Init: 
          config: 
            packages: 
              yum:
                httpd: []
                php: []
                wget: []
                unzip: []
                git: []
            commands:
              test:
                command: "wget https://www.tooplate.com/zip-templates/2119_gymso_fitness.zip && unzip 2119_gymso_fitness.zip && cp -r 2119_gymso_fitness/* /var/www/html/"

            sources: 
              :
            files: 
              /var/www/html/hello.html:
                content: !Sub |
                  <!DOCTYPE html>
                  <html>
                  <body>
                  <h1>Welcome to CloudFormation.</h1>
                  <p>This site is deployed by CloudFormation.</p>
                  </body>
                  </html>
            services: 
              sysvinit:
                httpd:
                  enabled: true
                  ensureRunning: true
      Properties:
          ImageId: !FindInMap
            - AMIRegionMap
            - !Ref AWS::Region
            - AMI
          KeyName: !Ref KeyPairName
          InstanceType: !Ref InstanceTypeParameter
          Tags:
            - 
              Key: Env
              Value: !Join ["-", [DEV, Environment]]
          SecurityGroups:
          - !Ref Ec2SecurityGroup
          UserData: 
           'Fn::Base64': 
            !Sub |
                #!/bin/bash -xe            
                # Ensure AWS CFN Bootstrap is the latest
                yum install -y aws-cfn-bootstrap
                # Install the files and packages from the metadata
                /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServer  --region ${AWS::Region}
                /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WebServer  --region ${AWS::Region}

          BlockDeviceMappings:
          -
            DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 50
          -
            DeviceName: /dev/sdm
            Ebs:
              VolumeSize: 100
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
Outputs:
  StackValue:
    Description: Output Values
    Value: !GetAtt.EC2Instance.PublicDnsName
    
